### Create User
POST http://localhost:4567/users
Content-Type: application/json

{
  "username": "arpitjaswal",
  "password": "password",
  "firstName": "Arpit",
  "lastName": "Jaswal",
  "email": "xyz@example.com",
  "age": 23
}

### Log In
POST http://localhost:4567/users/login
Content-Type: application/json

{
  "username": "arpitjaswal",
  "password": "password"
}

### Update User
PUT http://localhost:4567/users/1
Content-Type: application/json

{
  "username": "updatedarpitjaswal",
  "password": "updatedpassword"
}

### Delete User
DELETE http://localhost:4567/users/1

### Forgot Password
POST http://localhost:4567/users/forgotPassword
Content-Type: application/json

{
  "email": "xyz@example.com"
}
